default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  pool: 5
  database: <%= ServiceSettings.database.name %>
  host: <%= ServiceSettings.database.host %>
  username: <%= ServiceSettings.database.username %>
  password: <%= ServiceSettings.database.password %>

development:
  <<: *default
  database: <%= ServiceSettings.database.name %>_development

test:
  <<: *default
  database: <%= ServiceSettings.database.name %>_test

production:
  <<: *default
